### ISSUE TITLE
Difference with rappdirs::app_dir()?

### ISSUE THREAD

**Issue by maelle** [ropensci/hoardr#15]
What's the difference between your package and `rappdirs::app_dir()`?

**Comment by sckott** [comment]
goal is to add some convenience utiliities for managing cached files - all in just one R6 object - so you don't have to have many functions imported to manage cached files, but rather one object with methods on it

**Comment by maelle** [comment]
But what more methods compared to `rappdirs::app_dir()`?

**Comment by maelle** [comment]
``` r
ggplot2_app <- rappdirs::app_dir("hoardr", "sckott")
ggplot2_app$cache()
#> [1] "/home/maelle/.cache/hoardr"
ggplot2_app$log()
#> [1] "/home/maelle/.cache/hoardr/log"
ggplot2_app$data()
#> [1] "/home/maelle/.local/share/hoardr"
ggplot2_app$config()
#> [1] "/home/maelle/.config/hoardr"
ggplot2_app$site_config()
#> [1] "/etc/xdg/xdg-ubuntu/hoardr"
ggplot2_app$site_data()
#> [1] "/usr/share/ubuntu/hoardr"
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maelle** [comment]
Aaah the deletion, creation, etc. Sorry!

**Comment by sckott** [comment]
i had forgotten that rappdirs has a similar functionality. yes, hoardr added some additional stuff as you listed. just some bits on top of rappdirs, not substantially different
